name: sagecomm
favicon: null
layout_spectrum: 0.7886276983190328
typography_spectrum: 0.528112119063735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3134177771862596
  lightness: 0.18918029824271798
  saturation: 0.9455156077165157
  rhythmicContrast: 0.372764911968261
purpose: []
