name: sagecomm
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75949
title: This is a test site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#252b33'
    - '#fe5e25'
    - '#c9cacc'
    - '#8c8f93'
  brandStrength: 0.6875
  lightness: 0.18918029824271798
  saturation: 0.9455156077165157
  rhythmicContrast: 0.372764911968261
purpose: []
